networks:
  maeve-csms:
    name: maeve-csms
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1

services:
  manager:
    build: .
    expose:
      - 8080
    networks:
      - maeve-csms

  lb:
      image: envoyproxy/envoy:v1.26-latest
      command: ["-c", "/config/envoy.yaml"]
      volumes:
        - ./config/envoy:/config
      ports:
        - "8080:8080"
      depends_on:
        - manager
      networks:
        - maeve-csms
