services:
  alpine:
    image: alpine
    tty: true
    volumes:
      - ./foo:/foo
    user: "1000:1000"

  manager:
    build: .
    expose:
      - 8080
    ports:
      - "8081:8080"

  lb:
      image: envoyproxy/envoy:v1.26-latest
      command: ["-c", "/config/envoy.yaml"]
      volumes:
        - type: bind
          source: ./config/envoy
          target: /config
          read_only: true
      ports:
        - "8080:8080"


