networks:
  default:
    name: maeve-csms
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1

services:
  manager:
    build: .
    expose:
      - 8080

  lb:
      image: envoyproxy/envoy:v1.26-latest
      command: ["-c", "/config/envoy.yaml"]
      volumes:
        - ./config/envoy:/config
      ports:
        - "8080:8080"
